// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: standards/open/v1/frequency.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Standard frequency responses
type Frequency int32

const (
	Frequency_FREQUENCY_UNSPECIFIED Frequency = 0
	Frequency_DAILY                 Frequency = 1
	Frequency_WEEKLY                Frequency = 2
	Frequency_MONTHLY               Frequency = 3
	Frequency_QUARTERLY             Frequency = 4
	Frequency_BI_ANNUALLY           Frequency = 5
	Frequency_ANNUALLY              Frequency = 6
	Frequency_AD_HOC                Frequency = 7
)

// Enum value maps for Frequency.
var (
	Frequency_name = map[int32]string{
		0: "FREQUENCY_UNSPECIFIED",
		1: "DAILY",
		2: "WEEKLY",
		3: "MONTHLY",
		4: "QUARTERLY",
		5: "BI_ANNUALLY",
		6: "ANNUALLY",
		7: "AD_HOC",
	}
	Frequency_value = map[string]int32{
		"FREQUENCY_UNSPECIFIED": 0,
		"DAILY":                 1,
		"WEEKLY":                2,
		"MONTHLY":               3,
		"QUARTERLY":             4,
		"BI_ANNUALLY":           5,
		"ANNUALLY":              6,
		"AD_HOC":                7,
	}
)

func (x Frequency) Enum() *Frequency {
	p := new(Frequency)
	*p = x
	return p
}

func (x Frequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Frequency) Descriptor() protoreflect.EnumDescriptor {
	return file_standards_open_v1_frequency_proto_enumTypes[0].Descriptor()
}

func (Frequency) Type() protoreflect.EnumType {
	return &file_standards_open_v1_frequency_proto_enumTypes[0]
}

func (x Frequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Frequency.Descriptor instead.
func (Frequency) EnumDescriptor() ([]byte, []int) {
	return file_standards_open_v1_frequency_proto_rawDescGZIP(), []int{0}
}

var File_standards_open_v1_frequency_proto protoreflect.FileDescriptor

var file_standards_open_v1_frequency_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2a, 0x84, 0x01, 0x0a, 0x09, 0x46, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x52, 0x45, 0x51, 0x55, 0x45, 0x4e, 0x43,
	0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x44, 0x41, 0x49, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x45,
	0x45, 0x4b, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x4c,
	0x59, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x51, 0x55, 0x41, 0x52, 0x54, 0x45, 0x52, 0x4c, 0x59,
	0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x49, 0x5f, 0x41, 0x4e, 0x4e, 0x55, 0x41, 0x4c, 0x4c,
	0x59, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x4e, 0x4e, 0x55, 0x41, 0x4c, 0x4c, 0x59, 0x10,
	0x06, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x44, 0x5f, 0x48, 0x4f, 0x43, 0x10, 0x07, 0x42, 0x3d, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x6e,
	0x64, 0x61, 0x72, 0x64, 0x73, 0x2d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64,
	0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_standards_open_v1_frequency_proto_rawDescOnce sync.Once
	file_standards_open_v1_frequency_proto_rawDescData = file_standards_open_v1_frequency_proto_rawDesc
)

func file_standards_open_v1_frequency_proto_rawDescGZIP() []byte {
	file_standards_open_v1_frequency_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_frequency_proto_rawDescData = protoimpl.X.CompressGZIP(file_standards_open_v1_frequency_proto_rawDescData)
	})
	return file_standards_open_v1_frequency_proto_rawDescData
}

var file_standards_open_v1_frequency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_standards_open_v1_frequency_proto_goTypes = []interface{}{
	(Frequency)(0), // 0: standards.open.v1.Frequency
}
var file_standards_open_v1_frequency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_standards_open_v1_frequency_proto_init() }
func file_standards_open_v1_frequency_proto_init() {
	if File_standards_open_v1_frequency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_standards_open_v1_frequency_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_frequency_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_frequency_proto_depIdxs,
		EnumInfos:         file_standards_open_v1_frequency_proto_enumTypes,
	}.Build()
	File_standards_open_v1_frequency_proto = out.File
	file_standards_open_v1_frequency_proto_rawDesc = nil
	file_standards_open_v1_frequency_proto_goTypes = nil
	file_standards_open_v1_frequency_proto_depIdxs = nil
}
