// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: standards/open/v1/rag.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a Red / Amber / Green enumerator.
type RedAmberGreen int32

const (
	// The unspecifed designation.
	RedAmberGreen_RAG_UNSPECIFIED RedAmberGreen = 0
	// Red
	RedAmberGreen_RED RedAmberGreen = 1
	// Amber
	RedAmberGreen_AMBER RedAmberGreen = 2
	// Amber
	RedAmberGreen_GREEN RedAmberGreen = 3
)

// Enum value maps for RedAmberGreen.
var (
	RedAmberGreen_name = map[int32]string{
		0: "RAG_UNSPECIFIED",
		1: "RED",
		2: "AMBER",
		3: "GREEN",
	}
	RedAmberGreen_value = map[string]int32{
		"RAG_UNSPECIFIED": 0,
		"RED":             1,
		"AMBER":           2,
		"GREEN":           3,
	}
)

func (x RedAmberGreen) Enum() *RedAmberGreen {
	p := new(RedAmberGreen)
	*p = x
	return p
}

func (x RedAmberGreen) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RedAmberGreen) Descriptor() protoreflect.EnumDescriptor {
	return file_standards_open_v1_rag_proto_enumTypes[0].Descriptor()
}

func (RedAmberGreen) Type() protoreflect.EnumType {
	return &file_standards_open_v1_rag_proto_enumTypes[0]
}

func (x RedAmberGreen) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RedAmberGreen.Descriptor instead.
func (RedAmberGreen) EnumDescriptor() ([]byte, []int) {
	return file_standards_open_v1_rag_proto_rawDescGZIP(), []int{0}
}

var File_standards_open_v1_rag_proto protoreflect.FileDescriptor

var file_standards_open_v1_rag_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73,
	0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31,
	0x2a, 0x43, 0x0a, 0x0d, 0x52, 0x65, 0x64, 0x41, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x65, 0x65,
	0x6e, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x41, 0x47, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x41, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52,
	0x45, 0x45, 0x4e, 0x10, 0x03, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2d, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d,
	0x67, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_standards_open_v1_rag_proto_rawDescOnce sync.Once
	file_standards_open_v1_rag_proto_rawDescData = file_standards_open_v1_rag_proto_rawDesc
)

func file_standards_open_v1_rag_proto_rawDescGZIP() []byte {
	file_standards_open_v1_rag_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(file_standards_open_v1_rag_proto_rawDescData)
	})
	return file_standards_open_v1_rag_proto_rawDescData
}

var file_standards_open_v1_rag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_standards_open_v1_rag_proto_goTypes = []interface{}{
	(RedAmberGreen)(0), // 0: standards.open.v1.RedAmberGreen
}
var file_standards_open_v1_rag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_standards_open_v1_rag_proto_init() }
func file_standards_open_v1_rag_proto_init() {
	if File_standards_open_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_standards_open_v1_rag_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_rag_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_rag_proto_depIdxs,
		EnumInfos:         file_standards_open_v1_rag_proto_enumTypes,
	}.Build()
	File_standards_open_v1_rag_proto = out.File
	file_standards_open_v1_rag_proto_rawDesc = nil
	file_standards_open_v1_rag_proto_goTypes = nil
	file_standards_open_v1_rag_proto_depIdxs = nil
}
