// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: standards/open/v1/RT000YFB4.proto

package v1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CSSF report containing Identifiers of Luxembourg-based UCITS, compartments or share classes
type RT000YFB4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The records provided in the report
	Records []*RT000YFB4_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *RT000YFB4) Reset() {
	*x = RT000YFB4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standards_open_v1_RT000YFB4_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT000YFB4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000YFB4) ProtoMessage() {}

func (x *RT000YFB4) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000YFB4_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000YFB4.ProtoReflect.Descriptor instead.
func (*RT000YFB4) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000YFB4_proto_rawDescGZIP(), []int{0}
}

func (x *RT000YFB4) GetRecords() []*RT000YFB4_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Definition of an individual record in the report
type RT000YFB4_Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Metadata
	E string `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	// The CSSF's idenfifier for the umbrella
	Nnnnnnnn string `protobuf:"bytes,2,opt,name=nnnnnnnn,proto3" json:"nnnnnnnn,omitempty"`
	// The CSSF's idenfifier for the umbrella
	// NOMOPC
	UmbrellaNane string `protobuf:"bytes,3,opt,name=umbrella_nane,json=umbrellaNane,proto3" json:"umbrella_nane,omitempty"`
	// The CSSF's identifier for the fund
	Cccccccc string `protobuf:"bytes,4,opt,name=cccccccc,proto3" json:"cccccccc,omitempty"`
	// The name of the sub-fund / compartment
	// NOMCOMPARTIMENT
	Compartiment string `protobuf:"bytes,5,opt,name=compartiment,proto3" json:"compartiment,omitempty"`
	// AGREEMENTCOMP
	AgreementComp *date.Date `protobuf:"bytes,6,opt,name=agreement_comp,json=agreementComp,proto3" json:"agreement_comp,omitempty"`
	// DEVISECOMP
	DeviseComp string `protobuf:"bytes,7,opt,name=devise_comp,json=deviseComp,proto3" json:"devise_comp,omitempty"`
	// PPPP
	Pppp string `protobuf:"bytes,8,opt,name=pppp,proto3" json:"pppp,omitempty"`
	// NOMTYPEPART
	NomTypePart string `protobuf:"bytes,9,opt,name=nom_type_part,json=nomTypePart,proto3" json:"nom_type_part,omitempty"`
}

func (x *RT000YFB4_Record) Reset() {
	*x = RT000YFB4_Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standards_open_v1_RT000YFB4_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT000YFB4_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000YFB4_Record) ProtoMessage() {}

func (x *RT000YFB4_Record) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000YFB4_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000YFB4_Record.ProtoReflect.Descriptor instead.
func (*RT000YFB4_Record) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000YFB4_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RT000YFB4_Record) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *RT000YFB4_Record) GetNnnnnnnn() string {
	if x != nil {
		return x.Nnnnnnnn
	}
	return ""
}

func (x *RT000YFB4_Record) GetUmbrellaNane() string {
	if x != nil {
		return x.UmbrellaNane
	}
	return ""
}

func (x *RT000YFB4_Record) GetCccccccc() string {
	if x != nil {
		return x.Cccccccc
	}
	return ""
}

func (x *RT000YFB4_Record) GetCompartiment() string {
	if x != nil {
		return x.Compartiment
	}
	return ""
}

func (x *RT000YFB4_Record) GetAgreementComp() *date.Date {
	if x != nil {
		return x.AgreementComp
	}
	return nil
}

func (x *RT000YFB4_Record) GetDeviseComp() string {
	if x != nil {
		return x.DeviseComp
	}
	return ""
}

func (x *RT000YFB4_Record) GetPppp() string {
	if x != nil {
		return x.Pppp
	}
	return ""
}

func (x *RT000YFB4_Record) GetNomTypePart() string {
	if x != nil {
		return x.NomTypePart
	}
	return ""
}

var File_standards_open_v1_RT000YFB4_proto protoreflect.FileDescriptor

var file_standards_open_v1_RT000YFB4_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x52, 0x54, 0x30, 0x30, 0x30, 0x59, 0x46, 0x42, 0x34, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7,
	0x02, 0x0a, 0x09, 0x52, 0x54, 0x30, 0x30, 0x30, 0x59, 0x46, 0x42, 0x34, 0x12, 0x3d, 0x0a, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x54, 0x30, 0x30, 0x30, 0x59, 0x46, 0x42, 0x34, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0xaa, 0x02, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e,
	0x12, 0x23, 0x0a, 0x0d, 0x75, 0x6d, 0x62, 0x72, 0x65, 0x6c, 0x6c, 0x61, 0x5f, 0x6e, 0x61, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x6d, 0x62, 0x72, 0x65, 0x6c, 0x6c,
	0x61, 0x4e, 0x61, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63,
	0x63, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x0e, 0x61, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x52, 0x0d, 0x61, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x12,
	0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x70, 0x70, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x70, 0x70, 0x70, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x50, 0x61, 0x72, 0x74, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73,
	0x2d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f,
	0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_standards_open_v1_RT000YFB4_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT000YFB4_proto_rawDescData = file_standards_open_v1_RT000YFB4_proto_rawDesc
)

func file_standards_open_v1_RT000YFB4_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT000YFB4_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT000YFB4_proto_rawDescData = protoimpl.X.CompressGZIP(file_standards_open_v1_RT000YFB4_proto_rawDescData)
	})
	return file_standards_open_v1_RT000YFB4_proto_rawDescData
}

var file_standards_open_v1_RT000YFB4_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_v1_RT000YFB4_proto_goTypes = []interface{}{
	(*RT000YFB4)(nil),        // 0: standards.open.v1.RT000YFB4
	(*RT000YFB4_Record)(nil), // 1: standards.open.v1.RT000YFB4.Record
	(*date.Date)(nil),        // 2: google.type.Date
}
var file_standards_open_v1_RT000YFB4_proto_depIdxs = []int32{
	1, // 0: standards.open.v1.RT000YFB4.records:type_name -> standards.open.v1.RT000YFB4.Record
	2, // 1: standards.open.v1.RT000YFB4.Record.agreement_comp:type_name -> google.type.Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT000YFB4_proto_init() }
func file_standards_open_v1_RT000YFB4_proto_init() {
	if File_standards_open_v1_RT000YFB4_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_standards_open_v1_RT000YFB4_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT000YFB4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_standards_open_v1_RT000YFB4_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT000YFB4_Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_standards_open_v1_RT000YFB4_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT000YFB4_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT000YFB4_proto_depIdxs,
		MessageInfos:      file_standards_open_v1_RT000YFB4_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT000YFB4_proto = out.File
	file_standards_open_v1_RT000YFB4_proto_rawDesc = nil
	file_standards_open_v1_RT000YFB4_proto_goTypes = nil
	file_standards_open_v1_RT000YFB4_proto_depIdxs = nil
}
