// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: standards/open/v1/RT000T5C4.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CSSF report containing identifiers of registered ManCos
type RT000T5C4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The records provided in the report
	Records []*RT000T5C4_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *RT000T5C4) Reset() {
	*x = RT000T5C4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standards_open_v1_RT000T5C4_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT000T5C4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000T5C4) ProtoMessage() {}

func (x *RT000T5C4) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000T5C4_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000T5C4.ProtoReflect.Descriptor instead.
func (*RT000T5C4) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000T5C4_proto_rawDescGZIP(), []int{0}
}

func (x *RT000T5C4) GetRecords() []*RT000T5C4_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Definition of an individual record in the report
type RT000T5C4_Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The S or O code of the management company
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// The CSSF's indenfifier for the manco
	CssfIdentifier string `protobuf:"bytes,2,opt,name=cssf_identifier,json=cssfIdentifier,proto3" json:"cssf_identifier,omitempty"`
	// The name of the manco
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RT000T5C4_Record) Reset() {
	*x = RT000T5C4_Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standards_open_v1_RT000T5C4_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT000T5C4_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000T5C4_Record) ProtoMessage() {}

func (x *RT000T5C4_Record) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000T5C4_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000T5C4_Record.ProtoReflect.Descriptor instead.
func (*RT000T5C4_Record) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000T5C4_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RT000T5C4_Record) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RT000T5C4_Record) GetCssfIdentifier() string {
	if x != nil {
		return x.CssfIdentifier
	}
	return ""
}

func (x *RT000T5C4_Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_standards_open_v1_RT000T5C4_proto protoreflect.FileDescriptor

var file_standards_open_v1_RT000T5C4_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x52, 0x54, 0x30, 0x30, 0x30, 0x54, 0x35, 0x43, 0x34, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5,
	0x01, 0x0a, 0x09, 0x52, 0x54, 0x30, 0x30, 0x30, 0x54, 0x35, 0x43, 0x34, 0x12, 0x3d, 0x0a, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x54, 0x30, 0x30, 0x30, 0x54, 0x35, 0x43, 0x34, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x59, 0x0a, 0x06, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x73, 0x73,
	0x66, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x73, 0x73, 0x66, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2d, 0x65,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_standards_open_v1_RT000T5C4_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT000T5C4_proto_rawDescData = file_standards_open_v1_RT000T5C4_proto_rawDesc
)

func file_standards_open_v1_RT000T5C4_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT000T5C4_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT000T5C4_proto_rawDescData = protoimpl.X.CompressGZIP(file_standards_open_v1_RT000T5C4_proto_rawDescData)
	})
	return file_standards_open_v1_RT000T5C4_proto_rawDescData
}

var file_standards_open_v1_RT000T5C4_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_v1_RT000T5C4_proto_goTypes = []interface{}{
	(*RT000T5C4)(nil),        // 0: standards.open.v1.RT000T5C4
	(*RT000T5C4_Record)(nil), // 1: standards.open.v1.RT000T5C4.Record
}
var file_standards_open_v1_RT000T5C4_proto_depIdxs = []int32{
	1, // 0: standards.open.v1.RT000T5C4.records:type_name -> standards.open.v1.RT000T5C4.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT000T5C4_proto_init() }
func file_standards_open_v1_RT000T5C4_proto_init() {
	if File_standards_open_v1_RT000T5C4_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_standards_open_v1_RT000T5C4_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT000T5C4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_standards_open_v1_RT000T5C4_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT000T5C4_Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_standards_open_v1_RT000T5C4_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT000T5C4_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT000T5C4_proto_depIdxs,
		MessageInfos:      file_standards_open_v1_RT000T5C4_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT000T5C4_proto = out.File
	file_standards_open_v1_RT000T5C4_proto_rawDesc = nil
	file_standards_open_v1_RT000T5C4_proto_goTypes = nil
	file_standards_open_v1_RT000T5C4_proto_depIdxs = nil
}
