// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: standards/open/v1/RT000H944.proto

package v1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CSSF report containing Identifiers of Luxembourg-based UCI/SIF/SICAR compartments or share classes
type RT000H944 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The records provided in the report
	Records []*RT000H944_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *RT000H944) Reset() {
	*x = RT000H944{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standards_open_v1_RT000H944_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT000H944) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000H944) ProtoMessage() {}

func (x *RT000H944) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000H944_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000H944.ProtoReflect.Descriptor instead.
func (*RT000H944) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000H944_proto_rawDescGZIP(), []int{0}
}

func (x *RT000H944) GetRecords() []*RT000H944_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Definition of an individual record in the report
type RT000H944_Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Metadata
	E string `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	// The CSSF's idenfifier for the umbrella
	Nnnnnnnn string `protobuf:"bytes,2,opt,name=nnnnnnnn,proto3" json:"nnnnnnnn,omitempty"`
	// The CSSF's idenfifier for the umbrella
	// NOMOPC
	Nomopc string `protobuf:"bytes,3,opt,name=nomopc,proto3" json:"nomopc,omitempty"`
	// The CSSF's identifier for the fund
	Cccccccc string `protobuf:"bytes,4,opt,name=cccccccc,proto3" json:"cccccccc,omitempty"`
	// The name of the sub-fund / compartment
	// NOMCOMPARTIMENT
	Nomcompaortiment string `protobuf:"bytes,5,opt,name=nomcompaortiment,proto3" json:"nomcompaortiment,omitempty"`
	// AGREEMENTCOMP
	Agreementcomp *date.Date `protobuf:"bytes,6,opt,name=agreementcomp,proto3" json:"agreementcomp,omitempty"`
	// DEVISECOMP
	Devisecomp string `protobuf:"bytes,7,opt,name=devisecomp,proto3" json:"devisecomp,omitempty"`
	// PPPP
	Pppp string `protobuf:"bytes,8,opt,name=pppp,proto3" json:"pppp,omitempty"`
	// NOMTYPEPART
	Nomtypepart string `protobuf:"bytes,9,opt,name=nomtypepart,proto3" json:"nomtypepart,omitempty"`
}

func (x *RT000H944_Record) Reset() {
	*x = RT000H944_Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standards_open_v1_RT000H944_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT000H944_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT000H944_Record) ProtoMessage() {}

func (x *RT000H944_Record) ProtoReflect() protoreflect.Message {
	mi := &file_standards_open_v1_RT000H944_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT000H944_Record.ProtoReflect.Descriptor instead.
func (*RT000H944_Record) Descriptor() ([]byte, []int) {
	return file_standards_open_v1_RT000H944_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RT000H944_Record) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *RT000H944_Record) GetNnnnnnnn() string {
	if x != nil {
		return x.Nnnnnnnn
	}
	return ""
}

func (x *RT000H944_Record) GetNomopc() string {
	if x != nil {
		return x.Nomopc
	}
	return ""
}

func (x *RT000H944_Record) GetCccccccc() string {
	if x != nil {
		return x.Cccccccc
	}
	return ""
}

func (x *RT000H944_Record) GetNomcompaortiment() string {
	if x != nil {
		return x.Nomcompaortiment
	}
	return ""
}

func (x *RT000H944_Record) GetAgreementcomp() *date.Date {
	if x != nil {
		return x.Agreementcomp
	}
	return nil
}

func (x *RT000H944_Record) GetDevisecomp() string {
	if x != nil {
		return x.Devisecomp
	}
	return ""
}

func (x *RT000H944_Record) GetPppp() string {
	if x != nil {
		return x.Pppp
	}
	return ""
}

func (x *RT000H944_Record) GetNomtypepart() string {
	if x != nil {
		return x.Nomtypepart
	}
	return ""
}

var File_standards_open_v1_RT000H944_proto protoreflect.FileDescriptor

var file_standards_open_v1_RT000H944_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x52, 0x54, 0x30, 0x30, 0x30, 0x48, 0x39, 0x34, 0x34, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee,
	0x02, 0x0a, 0x09, 0x52, 0x54, 0x30, 0x30, 0x30, 0x48, 0x39, 0x34, 0x34, 0x12, 0x3d, 0x0a, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x54, 0x30, 0x30, 0x30, 0x48, 0x39, 0x34, 0x34, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0xa1, 0x02, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x6f, 0x70, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x6f, 0x70, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x63, 0x63, 0x63,
	0x63, 0x63, 0x63, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x63, 0x63, 0x63,
	0x63, 0x63, 0x63, 0x63, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x6f, 0x6d, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6f, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x6e, 0x6f, 0x6d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6f, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x37, 0x0a, 0x0d, 0x61, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x61, 0x67, 0x72, 0x65,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x70, 0x70,
	0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x70, 0x70, 0x70, 0x12, 0x20, 0x0a,
	0x0b, 0x6e, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x70, 0x61, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x70, 0x61, 0x72, 0x74, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_standards_open_v1_RT000H944_proto_rawDescOnce sync.Once
	file_standards_open_v1_RT000H944_proto_rawDescData = file_standards_open_v1_RT000H944_proto_rawDesc
)

func file_standards_open_v1_RT000H944_proto_rawDescGZIP() []byte {
	file_standards_open_v1_RT000H944_proto_rawDescOnce.Do(func() {
		file_standards_open_v1_RT000H944_proto_rawDescData = protoimpl.X.CompressGZIP(file_standards_open_v1_RT000H944_proto_rawDescData)
	})
	return file_standards_open_v1_RT000H944_proto_rawDescData
}

var file_standards_open_v1_RT000H944_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_open_v1_RT000H944_proto_goTypes = []interface{}{
	(*RT000H944)(nil),        // 0: standards.open.v1.RT000H944
	(*RT000H944_Record)(nil), // 1: standards.open.v1.RT000H944.Record
	(*date.Date)(nil),        // 2: google.type.Date
}
var file_standards_open_v1_RT000H944_proto_depIdxs = []int32{
	1, // 0: standards.open.v1.RT000H944.records:type_name -> standards.open.v1.RT000H944.Record
	2, // 1: standards.open.v1.RT000H944.Record.agreementcomp:type_name -> google.type.Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_standards_open_v1_RT000H944_proto_init() }
func file_standards_open_v1_RT000H944_proto_init() {
	if File_standards_open_v1_RT000H944_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_standards_open_v1_RT000H944_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT000H944); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_standards_open_v1_RT000H944_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT000H944_Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_standards_open_v1_RT000H944_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_open_v1_RT000H944_proto_goTypes,
		DependencyIndexes: file_standards_open_v1_RT000H944_proto_depIdxs,
		MessageInfos:      file_standards_open_v1_RT000H944_proto_msgTypes,
	}.Build()
	File_standards_open_v1_RT000H944_proto = out.File
	file_standards_open_v1_RT000H944_proto_rawDesc = nil
	file_standards_open_v1_RT000H944_proto_goTypes = nil
	file_standards_open_v1_RT000H944_proto_depIdxs = nil
}
