// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: RT0005M37.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/type/date"
	_ "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RT0005M37_YesNoExplain_Response int32

const (
	RT0005M37_YesNoExplain_RESPONSE_UNSPECIFIED RT0005M37_YesNoExplain_Response = 0
	RT0005M37_YesNoExplain_YES                  RT0005M37_YesNoExplain_Response = 1
	RT0005M37_YesNoExplain_NO                   RT0005M37_YesNoExplain_Response = 2
)

// Enum value maps for RT0005M37_YesNoExplain_Response.
var (
	RT0005M37_YesNoExplain_Response_name = map[int32]string{
		0: "RESPONSE_UNSPECIFIED",
		1: "YES",
		2: "NO",
	}
	RT0005M37_YesNoExplain_Response_value = map[string]int32{
		"RESPONSE_UNSPECIFIED": 0,
		"YES":                  1,
		"NO":                   2,
	}
)

func (x RT0005M37_YesNoExplain_Response) Enum() *RT0005M37_YesNoExplain_Response {
	p := new(RT0005M37_YesNoExplain_Response)
	*p = x
	return p
}

func (x RT0005M37_YesNoExplain_Response) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RT0005M37_YesNoExplain_Response) Descriptor() protoreflect.EnumDescriptor {
	return file_RT0005M37_proto_enumTypes[0].Descriptor()
}

func (RT0005M37_YesNoExplain_Response) Type() protoreflect.EnumType {
	return &file_RT0005M37_proto_enumTypes[0]
}

func (x RT0005M37_YesNoExplain_Response) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RT0005M37_YesNoExplain_Response.Descriptor instead.
func (RT0005M37_YesNoExplain_Response) EnumDescriptor() ([]byte, []int) {
	return file_RT0005M37_proto_rawDescGZIP(), []int{0, 0, 0}
}

type RT0005M37_YesExplainNo_Response int32

const (
	RT0005M37_YesExplainNo_RESPONSE_UNSPECIFIED RT0005M37_YesExplainNo_Response = 0
	RT0005M37_YesExplainNo_YES                  RT0005M37_YesExplainNo_Response = 1
	RT0005M37_YesExplainNo_NO                   RT0005M37_YesExplainNo_Response = 2
)

// Enum value maps for RT0005M37_YesExplainNo_Response.
var (
	RT0005M37_YesExplainNo_Response_name = map[int32]string{
		0: "RESPONSE_UNSPECIFIED",
		1: "YES",
		2: "NO",
	}
	RT0005M37_YesExplainNo_Response_value = map[string]int32{
		"RESPONSE_UNSPECIFIED": 0,
		"YES":                  1,
		"NO":                   2,
	}
)

func (x RT0005M37_YesExplainNo_Response) Enum() *RT0005M37_YesExplainNo_Response {
	p := new(RT0005M37_YesExplainNo_Response)
	*p = x
	return p
}

func (x RT0005M37_YesExplainNo_Response) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RT0005M37_YesExplainNo_Response) Descriptor() protoreflect.EnumDescriptor {
	return file_RT0005M37_proto_enumTypes[1].Descriptor()
}

func (RT0005M37_YesExplainNo_Response) Type() protoreflect.EnumType {
	return &file_RT0005M37_proto_enumTypes[1]
}

func (x RT0005M37_YesExplainNo_Response) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RT0005M37_YesExplainNo_Response.Descriptor instead.
func (RT0005M37_YesExplainNo_Response) EnumDescriptor() ([]byte, []int) {
	return file_RT0005M37_proto_rawDescGZIP(), []int{0, 1, 0}
}

type RT0005M37_YesNoAndExplain_Response int32

const (
	RT0005M37_YesNoAndExplain_RESPONSE_UNSPECIFIED RT0005M37_YesNoAndExplain_Response = 0
	RT0005M37_YesNoAndExplain_YES                  RT0005M37_YesNoAndExplain_Response = 1
	RT0005M37_YesNoAndExplain_NO                   RT0005M37_YesNoAndExplain_Response = 2
)

// Enum value maps for RT0005M37_YesNoAndExplain_Response.
var (
	RT0005M37_YesNoAndExplain_Response_name = map[int32]string{
		0: "RESPONSE_UNSPECIFIED",
		1: "YES",
		2: "NO",
	}
	RT0005M37_YesNoAndExplain_Response_value = map[string]int32{
		"RESPONSE_UNSPECIFIED": 0,
		"YES":                  1,
		"NO":                   2,
	}
)

func (x RT0005M37_YesNoAndExplain_Response) Enum() *RT0005M37_YesNoAndExplain_Response {
	p := new(RT0005M37_YesNoAndExplain_Response)
	*p = x
	return p
}

func (x RT0005M37_YesNoAndExplain_Response) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RT0005M37_YesNoAndExplain_Response) Descriptor() protoreflect.EnumDescriptor {
	return file_RT0005M37_proto_enumTypes[2].Descriptor()
}

func (RT0005M37_YesNoAndExplain_Response) Type() protoreflect.EnumType {
	return &file_RT0005M37_proto_enumTypes[2]
}

func (x RT0005M37_YesNoAndExplain_Response) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RT0005M37_YesNoAndExplain_Response.Descriptor instead.
func (RT0005M37_YesNoAndExplain_Response) EnumDescriptor() ([]byte, []int) {
	return file_RT0005M37_proto_rawDescGZIP(), []int{0, 2, 0}
}

// Wolfsberg Group Correspondent Banking Due Diligence Questionnaire (CBDDQ) V1.3.
// The questionnaire is required to be answered on a Legal Entity (LE) level. The Financial Institution should answer
// the questionnaire at the entity level including any branches for which the client base, products and control
// model are materially simialr to the LE Head Office. This Questionnaire should not cover more than one LE.
// Each question will need to be addressed from the perspective of the LE on behalf of all of its branches.
type RT0005M37 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the financial institution
	FinancialInstitutionName string `protobuf:"bytes,1,opt,name=financial_institution_name,json=financialInstitutionName,proto3" json:"financial_institution_name,omitempty"`
	// The three letter ISO code of the country in which the LE is located
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *RT0005M37) Reset() {
	*x = RT0005M37{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RT0005M37_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT0005M37) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT0005M37) ProtoMessage() {}

func (x *RT0005M37) ProtoReflect() protoreflect.Message {
	mi := &file_RT0005M37_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT0005M37.ProtoReflect.Descriptor instead.
func (*RT0005M37) Descriptor() ([]byte, []int) {
	return file_RT0005M37_proto_rawDescGZIP(), []int{0}
}

func (x *RT0005M37) GetFinancialInstitutionName() string {
	if x != nil {
		return x.FinancialInstitutionName
	}
	return ""
}

func (x *RT0005M37) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Response where a NO requires further information
type RT0005M37_YesNoExplain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Yes / No response.
	Response RT0005M37_YesNoExplain_Response `protobuf:"varint,1,opt,name=response,proto3,enum=standards.open.v1.RT0005M37_YesNoExplain_Response" json:"response,omitempty"`
	// Explanation if the answer is `NO`
	Explanation string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *RT0005M37_YesNoExplain) Reset() {
	*x = RT0005M37_YesNoExplain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RT0005M37_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT0005M37_YesNoExplain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT0005M37_YesNoExplain) ProtoMessage() {}

func (x *RT0005M37_YesNoExplain) ProtoReflect() protoreflect.Message {
	mi := &file_RT0005M37_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT0005M37_YesNoExplain.ProtoReflect.Descriptor instead.
func (*RT0005M37_YesNoExplain) Descriptor() ([]byte, []int) {
	return file_RT0005M37_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RT0005M37_YesNoExplain) GetResponse() RT0005M37_YesNoExplain_Response {
	if x != nil {
		return x.Response
	}
	return RT0005M37_YesNoExplain_RESPONSE_UNSPECIFIED
}

func (x *RT0005M37_YesNoExplain) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// Response where a YES requires further information
type RT0005M37_YesExplainNo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Yes / No response.
	Response RT0005M37_YesExplainNo_Response `protobuf:"varint,1,opt,name=response,proto3,enum=standards.open.v1.RT0005M37_YesExplainNo_Response" json:"response,omitempty"`
	// Explanation if the answer is `YES`
	Explanation string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *RT0005M37_YesExplainNo) Reset() {
	*x = RT0005M37_YesExplainNo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RT0005M37_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT0005M37_YesExplainNo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT0005M37_YesExplainNo) ProtoMessage() {}

func (x *RT0005M37_YesExplainNo) ProtoReflect() protoreflect.Message {
	mi := &file_RT0005M37_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT0005M37_YesExplainNo.ProtoReflect.Descriptor instead.
func (*RT0005M37_YesExplainNo) Descriptor() ([]byte, []int) {
	return file_RT0005M37_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RT0005M37_YesExplainNo) GetResponse() RT0005M37_YesExplainNo_Response {
	if x != nil {
		return x.Response
	}
	return RT0005M37_YesExplainNo_RESPONSE_UNSPECIFIED
}

func (x *RT0005M37_YesExplainNo) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// Response where further information is required regardless of whether a Yes or No is provided
type RT0005M37_YesNoAndExplain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Yes / No response.
	Response RT0005M37_YesNoAndExplain_Response `protobuf:"varint,1,opt,name=response,proto3,enum=standards.open.v1.RT0005M37_YesNoAndExplain_Response" json:"response,omitempty"`
	// Provide further information for the response
	Explanation string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *RT0005M37_YesNoAndExplain) Reset() {
	*x = RT0005M37_YesNoAndExplain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RT0005M37_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RT0005M37_YesNoAndExplain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RT0005M37_YesNoAndExplain) ProtoMessage() {}

func (x *RT0005M37_YesNoAndExplain) ProtoReflect() protoreflect.Message {
	mi := &file_RT0005M37_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RT0005M37_YesNoAndExplain.ProtoReflect.Descriptor instead.
func (*RT0005M37_YesNoAndExplain) Descriptor() ([]byte, []int) {
	return file_RT0005M37_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RT0005M37_YesNoAndExplain) GetResponse() RT0005M37_YesNoAndExplain_Response {
	if x != nil {
		return x.Response
	}
	return RT0005M37_YesNoAndExplain_RESPONSE_UNSPECIFIED
}

func (x *RT0005M37_YesNoAndExplain) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_RT0005M37_proto protoreflect.FileDescriptor

var file_RT0005M37_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x52, 0x54, 0x30, 0x30, 0x30, 0x35, 0x4d, 0x33, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x05, 0x0a, 0x09, 0x52, 0x54, 0x30, 0x30,
	0x30, 0x35, 0x4d, 0x33, 0x37, 0x12, 0x3c, 0x0a, 0x1a, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69,
	0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x66, 0x69, 0x6e, 0x61, 0x6e,
	0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0xb7, 0x01,
	0x0a, 0x0c, 0x59, 0x65, 0x73, 0x4e, 0x6f, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x4e,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x32, 0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x54, 0x30, 0x30, 0x30, 0x35, 0x4d, 0x33, 0x37, 0x2e, 0x59,
	0x65, 0x73, 0x4e, 0x6f, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x35, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x14,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x59, 0x45, 0x53, 0x10, 0x01, 0x12,
	0x06, 0x0a, 0x02, 0x4e, 0x4f, 0x10, 0x02, 0x1a, 0xb7, 0x01, 0x0a, 0x0c, 0x59, 0x65, 0x73, 0x45,
	0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x12, 0x4e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x73, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x54, 0x30, 0x30, 0x30, 0x35, 0x4d, 0x33, 0x37, 0x2e, 0x59, 0x65, 0x73, 0x45, 0x78, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c,
	0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e,
	0x53, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x59, 0x45, 0x53, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x4f, 0x10,
	0x02, 0x1a, 0xbd, 0x01, 0x0a, 0x0f, 0x59, 0x65, 0x73, 0x4e, 0x6f, 0x41, 0x6e, 0x64, 0x45, 0x78,
	0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x51, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61,
	0x72, 0x64, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x54, 0x30, 0x30,
	0x30, 0x35, 0x4d, 0x33, 0x37, 0x2e, 0x59, 0x65, 0x73, 0x4e, 0x6f, 0x41, 0x6e, 0x64, 0x45, 0x78,
	0x70, 0x6c, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c,
	0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e,
	0x53, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x59, 0x45, 0x53, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x4f, 0x10,
	0x02, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RT0005M37_proto_rawDescOnce sync.Once
	file_RT0005M37_proto_rawDescData = file_RT0005M37_proto_rawDesc
)

func file_RT0005M37_proto_rawDescGZIP() []byte {
	file_RT0005M37_proto_rawDescOnce.Do(func() {
		file_RT0005M37_proto_rawDescData = protoimpl.X.CompressGZIP(file_RT0005M37_proto_rawDescData)
	})
	return file_RT0005M37_proto_rawDescData
}

var file_RT0005M37_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_RT0005M37_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_RT0005M37_proto_goTypes = []interface{}{
	(RT0005M37_YesNoExplain_Response)(0),    // 0: standards.open.v1.RT0005M37.YesNoExplain.Response
	(RT0005M37_YesExplainNo_Response)(0),    // 1: standards.open.v1.RT0005M37.YesExplainNo.Response
	(RT0005M37_YesNoAndExplain_Response)(0), // 2: standards.open.v1.RT0005M37.YesNoAndExplain.Response
	(*RT0005M37)(nil),                       // 3: standards.open.v1.RT0005M37
	(*RT0005M37_YesNoExplain)(nil),          // 4: standards.open.v1.RT0005M37.YesNoExplain
	(*RT0005M37_YesExplainNo)(nil),          // 5: standards.open.v1.RT0005M37.YesExplainNo
	(*RT0005M37_YesNoAndExplain)(nil),       // 6: standards.open.v1.RT0005M37.YesNoAndExplain
}
var file_RT0005M37_proto_depIdxs = []int32{
	0, // 0: standards.open.v1.RT0005M37.YesNoExplain.response:type_name -> standards.open.v1.RT0005M37.YesNoExplain.Response
	1, // 1: standards.open.v1.RT0005M37.YesExplainNo.response:type_name -> standards.open.v1.RT0005M37.YesExplainNo.Response
	2, // 2: standards.open.v1.RT0005M37.YesNoAndExplain.response:type_name -> standards.open.v1.RT0005M37.YesNoAndExplain.Response
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_RT0005M37_proto_init() }
func file_RT0005M37_proto_init() {
	if File_RT0005M37_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RT0005M37_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT0005M37); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RT0005M37_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT0005M37_YesNoExplain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RT0005M37_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT0005M37_YesExplainNo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RT0005M37_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RT0005M37_YesNoAndExplain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RT0005M37_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RT0005M37_proto_goTypes,
		DependencyIndexes: file_RT0005M37_proto_depIdxs,
		EnumInfos:         file_RT0005M37_proto_enumTypes,
		MessageInfos:      file_RT0005M37_proto_msgTypes,
	}.Build()
	File_RT0005M37_proto = out.File
	file_RT0005M37_proto_rawDesc = nil
	file_RT0005M37_proto_goTypes = nil
	file_RT0005M37_proto_depIdxs = nil
}
